##
## motion/sensor.camera_lost.yaml
##

- platform: mqtt
  name: motion_camera_lost
  state_topic: 'motion/+/+/status/lost'
  qos: 2
  expire_after: 1
  force_update: True
  json_attributes:
    - device
    - camera
    - date
    - status
  value_template: >
    {% if value_json is defined %}True{% else %}null{% endif %}
