##
## motion/sensor.device_start.yaml.tmpl
##

- platform: mqtt
  name: motion_device_start
  qos: 2
  state_topic: 'motion/motion-master/start'
  json_attributes:
    - unit_system
    - latitude
    - longitude
    - elevation
    - interval
    - minimum_animate
    - post_pictures
    - share_dir
    - name
    - host
    - date
    - www
    - devicedb
    - timezone
    - mqtt
    - watson
    - digits
    - motion
    - cameras
  value_template: >
    {% if value_json is defined %}True{% else %}False{% endif %}
- platform: template
  sensors:
    motion_device_start_camera_count:
      entity_id:
        - sensor.motion_device_start
      value_template: >-
        {% if states.sensor.motion_device_start.attributes.cameras is defined %}
          {{ states.sensor.motion_device_start.attributes.cameras | length }}
        {% else %}null{% endif %}
    motion_device_start_camera_names:
      entity_id:
        - sensor.motion_device_start
      value_template: >-
        {% if states.sensor.motion_device_start.attributes.cameras is defined %}
          {%- for camera in states.sensor.motion_device_start.attributes.cameras -%}
            {% if loop.first %}[{% else %},{% endif %}
            {{- camera.name | tojson -}}
            {%- if loop.last -%}]{%- endif -%}
          {% endfor %}
        {% else %}null{% endif %}

