
# picture
- platform: template
  sensors:
    motion_noisesignal_picture:
      friendly_name: NOISE SIGNAL
      entity_id:
        - sensor.motion_base_url
      value_template: >-
          {% if states.sensor.motion_base_url|lower != 'none' and states.sensor.motion_base_url.state != 'unknown' %}
            {{ states.sensor.motion_base_url.state + '/local/images/noise-signal.png' }}
          {% else %}{{ null }}{% endif %}
