
# picture
- platform: template
  sensors:
    motion_nosignal_picture:
      friendly_name: NO SIGNAL
      entity_id:
        - sensor.motion_base_url
      value_template: >-
          {% if states.sensor.motion_base_url|lower != 'none' and states.sensor.motion_base_url.state != 'unknown' %}
            {{ states.sensor.motion_base_url.state + '/local/images/no-signal.jpg' }}
          {% else %}{{ null }}{% endif %}
