##
## EVENT ANNOTATED
##

- platform: template
  sensors:
    motion_annotated:
      entity_id:
        - sensor.motion_event_annotated
      value_template: >
        {{ states('sensor.motion_event_annotated')|lower == 'true' }}
