###
### detected_entity BINARY_SENSOR
###

- platform: template
  sensors:
    motion_detected_entity:
      entity_id:
        - sensor.motion_annotated_entity_count
      value_template: >-
        {{ states('sensor.motion_annotated_entity_count')|int > 0 }}

###
### class detection
###

- platform: template
  sensors:
    motion_detected_person:
      entity_id:
        - binary_sensor.motion_detected
        - sensor.motion_detected_ago
      value_template: >-
        {% if states.sensor.motion_event_annotated|lower != 'none' 
              and states.sensor.motion_detected_person.state|lower != 'unknown'
              and states.sensor.motion_detected_person.state|lower != 'none'
              and states.sensor.motion_detected_person.state|from_json != 'null'
              and states.sensor.motion_detected_person.state|from_json is iterable %}
          {{ states.sensor.motion_detected_person.state|from_json|sum|int > 0 }}
        {% else %}null{% endif %}

- platform: template
  sensors:
    motion_detected_vehicle:
      entity_id:
        - binary_sensor.motion_detected
        - sensor.motion_detected_ago
      value_template: >-
        {% if states.sensor.motion_event_annotated|lower != 'none'
              and states.sensor.motion_detected_vehicle.state|lower != 'none'
              and states.sensor.motion_detected_vehicle.state|lower != 'unknown'
              and states.sensor.motion_detected_vehicle.state|from_json != 'null'
              and states.sensor.motion_detected_vehicle.state|from_json is iterable %}
          {{ states.sensor.motion_detected_vehicle.state|from_json|sum|int > 0 }}
        {% else %}null{% endif %}

- platform: template
  sensors:
    motion_detected_animal:
      entity_id:
        - binary_sensor.motion_detected
        - sensor.motion_detected_ago
      value_template: >-
        {% if states.sensor.motion_event_annotated|lower != 'none' 
              and states.sensor.motion_detected_animal.state|lower != 'none'
              and states.sensor.motion_detected_animal.state|lower != 'unknown'
              and states.sensor.motion_detected_animal.state|from_json != 'null' 
              and states.sensor.motion_detected_animal.state|from_json is iterable %}
          {{ states.sensor.motion_detected_animal.state|from_json|sum|int > 0 }}
        {% else %}null{% endif %}
