###
### EVENT END
###

- platform: template
  sensors:
    motion_end:
      entity_id:
        - sensor.motion_event_end
      value_template: >
        {{ states('sensor.motion_event_end')|lower == 'true' }}
