###
### EVENT IMAGE
###

- platform: template
  sensors:
    motion_image_state:
      entity_id:
        - sensor.motion_event_image
      value_template: >
        {{ states('sensor.motion_event_image')|lower == 'true' }}
