###
### motion_poolcam BINARY_SENSOR
###

- platform: template
  sensors:
    motion_end_poolcam:
      friendly_name: poolcam end
      entity_id:
        - sensor.motion_event_end_poolcam
      value_template: >
        {{ states('sensor.motion_event_end_poolcam')|lower == 'true' }}

- platform: template
  sensors:
    motion_annotated_poolcam:
      friendly_name: poolcam annotated
      entity_id:
        - sensor.motion_event_annotated_poolcam
      value_template: >
        {{ states('sensor.motion_event_annotated_poolcam')|lower == 'true' }}

- platform: template
  sensors:
    motion_detected_poolcam:
      friendly_name: poolcam detected
      entity_id:
        - sensor.motion_annotated_count_poolcam
      value_template: >
        {{ states('sensor.motion_annotated_count_poolcam')|int > 0 }}

- platform: template
  sensors:
    motion_detected_entity_poolcam:
      friendly_name: poolcam detected entity
      entity_id:
        - sensor.motion_annotated_entity_count_poolcam
      value_template: >-
        {{ states('sensor.motion_annotated_entity_count_poolcam')|int > 0 }}

##

- platform: template
  sensors:
    motion_complete_poolcam:
      friendly_name: poolcam complete
      entity_id:
        - sensor.motion_complete_poolcam
      value_template: >
        {% set d = states('sensor.motion_complete_poolcam')|int %}
        {{ d > 0 and d < states('input_number.motion_complete')|int }}

##

- platform: template
  sensors:
    motion_detected_person_poolcam:
      entity_id:
        - binary_sensor.motion_detected_poolcam
        - sensor.motion_detected_ago_poolcam
      value_template: >-
        {% if states.sensor.motion_event_annotated_poolcam|lower != 'none'
              and states.sensor.motion_detected_person_poolcam.state|lower != 'unknown'
              and states.sensor.motion_detected_person_poolcam.state|lower != 'none'
              and states.sensor.motion_detected_person_poolcam.state|from_json != 'null'
              and states.sensor.motion_detected_person_poolcam.state|from_json is iterable %}
          {{ states.sensor.motion_detected_person_poolcam.state|from_json|sum|int > 0 }}
        {% else %}null{% endif %}

- platform: template
  sensors:
    motion_detected_vehicle_poolcam:
      entity_id:
        - binary_sensor.motion_detected_poolcam
        - sensor.motion_detected_ago_poolcam
      value_template: >-
        {% if states.sensor.motion_event_annotated_poolcam|lower != 'none'
              and states.sensor.motion_detected_vehicle_poolcam.state|lower != 'none'
              and states.sensor.motion_detected_vehicle_poolcam.state|lower != 'unknown'
              and states.sensor.motion_detected_vehicle_poolcam.state|from_json != 'null'
              and states.sensor.motion_detected_vehicle_poolcam.state|from_json is iterable %}
          {{ states.sensor.motion_detected_vehicle_poolcam.state|from_json|sum|int > 0 }}
        {% else %}null{% endif %}

- platform: template
  sensors:
    motion_detected_animal_poolcam:
      entity_id:
        - binary_sensor.motion_detected_poolcam
        - sensor.motion_detected_ago_poolcam
      value_template: >-
        {% if states.sensor.motion_event_annotated_poolcam|lower != 'none'
              and states.sensor.motion_detected_animal_poolcam.state|lower != 'none'
              and states.sensor.motion_detected_animal_poolcam.state|lower != 'unknown'
              and states.sensor.motion_detected_animal_poolcam.state|from_json != 'null'
              and states.sensor.motion_detected_animal_poolcam.state|from_json is iterable %}
          {{ states.sensor.motion_detected_animal_poolcam.state|from_json|sum|int > 0 }}
        {% else %}null{% endif %}
