###
### motion_dogpond BINARY_SENSOR
###

- platform: template
  sensors:
    motion_end_dogpond:
      friendly_name: dogpond end
      entity_id:
        - sensor.motion_event_end_dogpond
      value_template: >
        {{ states('sensor.motion_event_end_dogpond')|lower == 'true' }}

- platform: template
  sensors:
    motion_annotated_dogpond:
      friendly_name: dogpond annotated
      entity_id:
        - sensor.motion_event_annotated_dogpond
      value_template: >
        {{ states('sensor.motion_event_annotated_dogpond')|lower == 'true' }}

- platform: template
  sensors:
    motion_detected_dogpond:
      friendly_name: dogpond detected
      entity_id:
        - sensor.motion_annotated_count_dogpond
      value_template: >
        {{ states('sensor.motion_annotated_count_dogpond')|int > 0 }}

- platform: template
  sensors:
    motion_detected_entity_dogpond:
      friendly_name: dogpond detected entity
      entity_id:
        - sensor.motion_annotated_entity_count_dogpond
      value_template: >-
        {{ states('sensor.motion_annotated_entity_count_dogpond')|int > 0 }}

##

- platform: template
  sensors:
    motion_complete_dogpond:
      friendly_name: dogpond complete
      entity_id:
        - sensor.motion_complete_dogpond
      value_template: >
        {% set d = states('sensor.motion_complete_dogpond')|int %}
        {{ d > 0 and d < states('input_number.motion_complete')|int }}

##

- platform: template
  sensors:
    motion_detected_person_dogpond:
      entity_id:
        - binary_sensor.motion_detected_dogpond
        - sensor.motion_detected_ago_dogpond
      value_template: >-
        {% if states.sensor.motion_event_annotated_dogpond|lower != 'none'
              and states.sensor.motion_detected_person_dogpond.state|lower != 'unknown'
              and states.sensor.motion_detected_person_dogpond.state|lower != 'none'
              and states.sensor.motion_detected_person_dogpond.state|from_json != 'null'
              and states.sensor.motion_detected_person_dogpond.state|from_json is iterable %}
          {{ states.sensor.motion_detected_person_dogpond.state|from_json|sum|int > 0 }}
        {% else %}null{% endif %}

- platform: template
  sensors:
    motion_detected_vehicle_dogpond:
      entity_id:
        - binary_sensor.motion_detected_dogpond
        - sensor.motion_detected_ago_dogpond
      value_template: >-
        {% if states.sensor.motion_event_annotated_dogpond|lower != 'none'
              and states.sensor.motion_detected_vehicle_dogpond.state|lower != 'none'
              and states.sensor.motion_detected_vehicle_dogpond.state|lower != 'unknown'
              and states.sensor.motion_detected_vehicle_dogpond.state|from_json != 'null'
              and states.sensor.motion_detected_vehicle_dogpond.state|from_json is iterable %}
          {{ states.sensor.motion_detected_vehicle_dogpond.state|from_json|sum|int > 0 }}
        {% else %}null{% endif %}

- platform: template
  sensors:
    motion_detected_animal_dogpond:
      entity_id:
        - binary_sensor.motion_detected_dogpond
        - sensor.motion_detected_ago_dogpond
      value_template: >-
        {% if states.sensor.motion_event_annotated_dogpond|lower != 'none'
              and states.sensor.motion_detected_animal_dogpond.state|lower != 'none'
              and states.sensor.motion_detected_animal_dogpond.state|lower != 'unknown'
              and states.sensor.motion_detected_animal_dogpond.state|from_json != 'null'
              and states.sensor.motion_detected_animal_dogpond.state|from_json is iterable %}
          {{ states.sensor.motion_detected_animal_dogpond.state|from_json|sum|int > 0 }}
        {% else %}null{% endif %}
