###
### motion_sideyard BINARY_SENSOR
###

- platform: template
  sensors:
    motion_end_sideyard:
      friendly_name: sideyard end
      entity_id:
        - sensor.motion_event_end_sideyard
      value_template: >
        {{ states('sensor.motion_event_end_sideyard')|lower == 'true' }}

- platform: template
  sensors:
    motion_annotated_sideyard:
      friendly_name: sideyard annotated
      entity_id:
        - sensor.motion_event_annotated_sideyard
      value_template: >
        {{ states('sensor.motion_event_annotated_sideyard')|lower == 'true' }}

- platform: template
  sensors:
    motion_detected_sideyard:
      friendly_name: sideyard detected
      entity_id:
        - sensor.motion_annotated_count_sideyard
      value_template: >
        {{ states('sensor.motion_annotated_count_sideyard')|int > 0 }}

- platform: template
  sensors:
    motion_detected_entity_sideyard:
      friendly_name: sideyard detected entity
      entity_id:
        - sensor.motion_annotated_entity_count_sideyard
      value_template: >-
        {{ states('sensor.motion_annotated_entity_count_sideyard')|int > 0 }}

##

- platform: template
  sensors:
    motion_complete_sideyard:
      friendly_name: sideyard complete
      entity_id:
        - sensor.motion_complete_sideyard
      value_template: >
        {% set d = states('sensor.motion_complete_sideyard')|int %}
        {{ d > 0 and d < states('input_number.motion_complete')|int }}

##

- platform: template
  sensors:
    motion_detected_person_sideyard:
      entity_id:
        - binary_sensor.motion_detected_sideyard
        - sensor.motion_detected_ago_sideyard
      value_template: >-
        {% if states.sensor.motion_event_annotated_sideyard|lower != 'none'
              and states.sensor.motion_detected_person_sideyard.state|lower != 'unknown'
              and states.sensor.motion_detected_person_sideyard.state|lower != 'none'
              and states.sensor.motion_detected_person_sideyard.state|from_json != 'null'
              and states.sensor.motion_detected_person_sideyard.state|from_json is iterable %}
          {{ states.sensor.motion_detected_person_sideyard.state|from_json|sum|int > 0 }}
        {% else %}null{% endif %}

- platform: template
  sensors:
    motion_detected_vehicle_sideyard:
      entity_id:
        - binary_sensor.motion_detected_sideyard
        - sensor.motion_detected_ago_sideyard
      value_template: >-
        {% if states.sensor.motion_event_annotated_sideyard|lower != 'none'
              and states.sensor.motion_detected_vehicle_sideyard.state|lower != 'none'
              and states.sensor.motion_detected_vehicle_sideyard.state|lower != 'unknown'
              and states.sensor.motion_detected_vehicle_sideyard.state|from_json != 'null'
              and states.sensor.motion_detected_vehicle_sideyard.state|from_json is iterable %}
          {{ states.sensor.motion_detected_vehicle_sideyard.state|from_json|sum|int > 0 }}
        {% else %}null{% endif %}

- platform: template
  sensors:
    motion_detected_animal_sideyard:
      entity_id:
        - binary_sensor.motion_detected_sideyard
        - sensor.motion_detected_ago_sideyard
      value_template: >-
        {% if states.sensor.motion_event_annotated_sideyard|lower != 'none'
              and states.sensor.motion_detected_animal_sideyard.state|lower != 'none'
              and states.sensor.motion_detected_animal_sideyard.state|lower != 'unknown'
              and states.sensor.motion_detected_animal_sideyard.state|from_json != 'null'
              and states.sensor.motion_detected_animal_sideyard.state|from_json is iterable %}
          {{ states.sensor.motion_detected_animal_sideyard.state|from_json|sum|int > 0 }}
        {% else %}null{% endif %}
