###
# motion/binary_sensor/webcams.yaml
###

- platform: template
  sensors:
    motion_detected_entity_webcams:
      entity_id:
        - group.motion_detected_entity
      value_template: >
        {% if states.group.motion_detected_entity|lower != 'none'
              and state_attr('group.motion_detected_entity','entity_id')|lower != 'none'
              and states.group.motion_detected_entity.attributes.entity_id|list|length > 0 %}
          {{ states.group.motion_detected_entity.state }}
        {% else %}null{% endif %}

- platform: template
  sensors:
    motion_detected_webcams:
      entity_id:
        - group.motion_detected
      value_template: >
        {% if states.group.motion_detected|lower != 'none'
              and state_attr('group.motion_detected','entity_id')|lower != 'none'
              and states.group.motion_detected.attributes.entity_id|list|length > 0 %}
          {{ states.group.motion_detected.state }}
        {% else %}null{% endif %}

- platform: template
  sensors:
    motion_annotated_webcams:
      entity_id:
        - group.motion_annotated
      value_template: >
        {% if states.group.motion_annotated|lower != 'none'
              and state_attr('group.motion_annotated','entity_id')|lower != 'none'
              and states.group.motion_annotated.attributes.entity_id|list|length > 0 %}
          {{ states.group.motion_annotated.state }}
        {% else %}null{% endif %}

- platform: template
  sensors:
    motion_end_webcams:
      entity_id:
        - group.motion_end
      value_template: >
        {% if states.group.motion_end|lower != 'none'
              and state_attr('group.motion_end','entity_id')|lower != 'none'
              and states.group.motion_end.attributes.entity_id|list|length > 0 %}
          {{ states.group.motion_end.state }}
        {% else %}null{% endif %}
