###
### motion_dogshedfront BINARY_SENSOR
###

- platform: template
  sensors:
    motion_end_dogshedfront:
      friendly_name: dogshedfront end
      entity_id:
        - sensor.motion_event_end_dogshedfront
      value_template: >
        {{ states('sensor.motion_event_end_dogshedfront')|lower == 'true' }}

- platform: template
  sensors:
    motion_annotated_dogshedfront:
      friendly_name: dogshedfront annotated
      entity_id:
        - sensor.motion_event_annotated_dogshedfront
      value_template: >
        {{ states('sensor.motion_event_annotated_dogshedfront')|lower == 'true' }}

- platform: template
  sensors:
    motion_detected_dogshedfront:
      friendly_name: dogshedfront detected
      entity_id:
        - sensor.motion_annotated_count_dogshedfront
      value_template: >
        {{ states('sensor.motion_annotated_count_dogshedfront')|int > 0 }}

- platform: template
  sensors:
    motion_detected_entity_dogshedfront:
      friendly_name: dogshedfront detected entity
      entity_id:
        - sensor.motion_annotated_entity_count_dogshedfront
      value_template: >-
        {{ states('sensor.motion_annotated_entity_count_dogshedfront')|int > 0 }}

##

- platform: template
  sensors:
    motion_complete_dogshedfront:
      friendly_name: dogshedfront complete
      entity_id:
        - sensor.motion_complete_dogshedfront
      value_template: >
        {% set d = states('sensor.motion_complete_dogshedfront')|int %}
        {{ d > 0 and d < states('input_number.motion_complete')|int }}

##

- platform: template
  sensors:
    motion_detected_person_dogshedfront:
      entity_id:
        - binary_sensor.motion_detected_dogshedfront
        - sensor.motion_detected_ago_dogshedfront
      value_template: >-
        {% if states.sensor.motion_event_annotated_dogshedfront|lower != 'none'
              and states.sensor.motion_detected_person_dogshedfront.state|lower != 'unknown'
              and states.sensor.motion_detected_person_dogshedfront.state|lower != 'none'
              and states.sensor.motion_detected_person_dogshedfront.state|from_json != 'null'
              and states.sensor.motion_detected_person_dogshedfront.state|from_json is iterable %}
          {{ states.sensor.motion_detected_person_dogshedfront.state|from_json|sum|int > 0 }}
        {% else %}null{% endif %}

- platform: template
  sensors:
    motion_detected_vehicle_dogshedfront:
      entity_id:
        - binary_sensor.motion_detected_dogshedfront
        - sensor.motion_detected_ago_dogshedfront
      value_template: >-
        {% if states.sensor.motion_event_annotated_dogshedfront|lower != 'none'
              and states.sensor.motion_detected_vehicle_dogshedfront.state|lower != 'none'
              and states.sensor.motion_detected_vehicle_dogshedfront.state|lower != 'unknown'
              and states.sensor.motion_detected_vehicle_dogshedfront.state|from_json != 'null'
              and states.sensor.motion_detected_vehicle_dogshedfront.state|from_json is iterable %}
          {{ states.sensor.motion_detected_vehicle_dogshedfront.state|from_json|sum|int > 0 }}
        {% else %}null{% endif %}

- platform: template
  sensors:
    motion_detected_animal_dogshedfront:
      entity_id:
        - binary_sensor.motion_detected_dogshedfront
        - sensor.motion_detected_ago_dogshedfront
      value_template: >-
        {% if states.sensor.motion_event_annotated_dogshedfront|lower != 'none'
              and states.sensor.motion_detected_animal_dogshedfront.state|lower != 'none'
              and states.sensor.motion_detected_animal_dogshedfront.state|lower != 'unknown'
              and states.sensor.motion_detected_animal_dogshedfront.state|from_json != 'null'
              and states.sensor.motion_detected_animal_dogshedfront.state|from_json is iterable %}
          {{ states.sensor.motion_detected_animal_dogshedfront.state|from_json|sum|int > 0 }}
        {% else %}null{% endif %}
