###
### motion_interiorgate BINARY_SENSOR
###

- platform: template
  sensors:
    motion_end_interiorgate:
      friendly_name: interiorgate end
      entity_id:
        - sensor.motion_event_end_interiorgate
      value_template: >
        {{ states('sensor.motion_event_end_interiorgate')|lower == 'true' }}

- platform: template
  sensors:
    motion_annotated_interiorgate:
      friendly_name: interiorgate annotated
      entity_id:
        - sensor.motion_event_annotated_interiorgate
      value_template: >
        {{ states('sensor.motion_event_annotated_interiorgate')|lower == 'true' }}

- platform: template
  sensors:
    motion_detected_interiorgate:
      friendly_name: interiorgate detected
      entity_id:
        - sensor.motion_annotated_count_interiorgate
      value_template: >
        {{ states('sensor.motion_annotated_count_interiorgate')|int > 0 }}

- platform: template
  sensors:
    motion_detected_entity_interiorgate:
      friendly_name: interiorgate detected entity
      entity_id:
        - sensor.motion_annotated_entity_count_interiorgate
      value_template: >-
        {{ states('sensor.motion_annotated_entity_count_interiorgate')|int > 0 }}

##

- platform: template
  sensors:
    motion_complete_interiorgate:
      friendly_name: interiorgate complete
      entity_id:
        - sensor.motion_complete_interiorgate
      value_template: >
        {% set d = states('sensor.motion_complete_interiorgate')|int %}
        {{ d > 0 and d < states('input_number.motion_complete')|int }}

##

- platform: template
  sensors:
    motion_detected_person_interiorgate:
      entity_id:
        - binary_sensor.motion_detected_interiorgate
        - sensor.motion_detected_ago_interiorgate
      value_template: >-
        {% if states.sensor.motion_event_annotated_interiorgate|lower != 'none'
              and states.sensor.motion_detected_person_interiorgate.state|lower != 'unknown'
              and states.sensor.motion_detected_person_interiorgate.state|lower != 'none'
              and states.sensor.motion_detected_person_interiorgate.state|from_json != 'null'
              and states.sensor.motion_detected_person_interiorgate.state|from_json is iterable %}
          {{ states.sensor.motion_detected_person_interiorgate.state|from_json|sum|int > 0 }}
        {% else %}null{% endif %}

- platform: template
  sensors:
    motion_detected_vehicle_interiorgate:
      entity_id:
        - binary_sensor.motion_detected_interiorgate
        - sensor.motion_detected_ago_interiorgate
      value_template: >-
        {% if states.sensor.motion_event_annotated_interiorgate|lower != 'none'
              and states.sensor.motion_detected_vehicle_interiorgate.state|lower != 'none'
              and states.sensor.motion_detected_vehicle_interiorgate.state|lower != 'unknown'
              and states.sensor.motion_detected_vehicle_interiorgate.state|from_json != 'null'
              and states.sensor.motion_detected_vehicle_interiorgate.state|from_json is iterable %}
          {{ states.sensor.motion_detected_vehicle_interiorgate.state|from_json|sum|int > 0 }}
        {% else %}null{% endif %}

- platform: template
  sensors:
    motion_detected_animal_interiorgate:
      entity_id:
        - binary_sensor.motion_detected_interiorgate
        - sensor.motion_detected_ago_interiorgate
      value_template: >-
        {% if states.sensor.motion_event_annotated_interiorgate|lower != 'none'
              and states.sensor.motion_detected_animal_interiorgate.state|lower != 'none'
              and states.sensor.motion_detected_animal_interiorgate.state|lower != 'unknown'
              and states.sensor.motion_detected_animal_interiorgate.state|from_json != 'null'
              and states.sensor.motion_detected_animal_interiorgate.state|from_json is iterable %}
          {{ states.sensor.motion_detected_animal_interiorgate.state|from_json|sum|int > 0 }}
        {% else %}null{% endif %}
