###
### motion_dogshedmiddle BINARY_SENSOR
###

- platform: template
  sensors:
    motion_end_dogshedmiddle:
      friendly_name: dogshedmiddle end
      entity_id:
        - sensor.motion_event_end_dogshedmiddle
      value_template: >
        {{ states('sensor.motion_event_end_dogshedmiddle')|lower == 'true' }}

- platform: template
  sensors:
    motion_annotated_dogshedmiddle:
      friendly_name: dogshedmiddle annotated
      entity_id:
        - sensor.motion_event_annotated_dogshedmiddle
      value_template: >
        {{ states('sensor.motion_event_annotated_dogshedmiddle')|lower == 'true' }}

- platform: template
  sensors:
    motion_detected_dogshedmiddle:
      friendly_name: dogshedmiddle detected
      entity_id:
        - sensor.motion_annotated_count_dogshedmiddle
      value_template: >
        {{ states('sensor.motion_annotated_count_dogshedmiddle')|int > 0 }}

- platform: template
  sensors:
    motion_detected_entity_dogshedmiddle:
      friendly_name: dogshedmiddle detected entity
      entity_id:
        - sensor.motion_annotated_entity_count_dogshedmiddle
      value_template: >-
        {{ states('sensor.motion_annotated_entity_count_dogshedmiddle')|int > 0 }}

##

- platform: template
  sensors:
    motion_complete_dogshedmiddle:
      friendly_name: dogshedmiddle complete
      entity_id:
        - sensor.motion_complete_dogshedmiddle
      value_template: >
        {% set d = states('sensor.motion_complete_dogshedmiddle')|int %}
        {{ d > 0 and d < states('input_number.motion_complete')|int }}

##

- platform: template
  sensors:
    motion_detected_person_dogshedmiddle:
      entity_id:
        - binary_sensor.motion_detected_dogshedmiddle
        - sensor.motion_detected_ago_dogshedmiddle
      value_template: >-
        {% if states.sensor.motion_event_annotated_dogshedmiddle|lower != 'none'
              and states.sensor.motion_detected_person_dogshedmiddle.state|lower != 'unknown'
              and states.sensor.motion_detected_person_dogshedmiddle.state|lower != 'none'
              and states.sensor.motion_detected_person_dogshedmiddle.state|from_json != 'null'
              and states.sensor.motion_detected_person_dogshedmiddle.state|from_json is iterable %}
          {{ states.sensor.motion_detected_person_dogshedmiddle.state|from_json|sum|int > 0 }}
        {% else %}null{% endif %}

- platform: template
  sensors:
    motion_detected_vehicle_dogshedmiddle:
      entity_id:
        - binary_sensor.motion_detected_dogshedmiddle
        - sensor.motion_detected_ago_dogshedmiddle
      value_template: >-
        {% if states.sensor.motion_event_annotated_dogshedmiddle|lower != 'none'
              and states.sensor.motion_detected_vehicle_dogshedmiddle.state|lower != 'none'
              and states.sensor.motion_detected_vehicle_dogshedmiddle.state|lower != 'unknown'
              and states.sensor.motion_detected_vehicle_dogshedmiddle.state|from_json != 'null'
              and states.sensor.motion_detected_vehicle_dogshedmiddle.state|from_json is iterable %}
          {{ states.sensor.motion_detected_vehicle_dogshedmiddle.state|from_json|sum|int > 0 }}
        {% else %}null{% endif %}

- platform: template
  sensors:
    motion_detected_animal_dogshedmiddle:
      entity_id:
        - binary_sensor.motion_detected_dogshedmiddle
        - sensor.motion_detected_ago_dogshedmiddle
      value_template: >-
        {% if states.sensor.motion_event_annotated_dogshedmiddle|lower != 'none'
              and states.sensor.motion_detected_animal_dogshedmiddle.state|lower != 'none'
              and states.sensor.motion_detected_animal_dogshedmiddle.state|lower != 'unknown'
              and states.sensor.motion_detected_animal_dogshedmiddle.state|from_json != 'null'
              and states.sensor.motion_detected_animal_dogshedmiddle.state|from_json is iterable %}
          {{ states.sensor.motion_detected_animal_dogshedmiddle.state|from_json|sum|int > 0 }}
        {% else %}null{% endif %}
