##
## end CAMERA
##

# per event
- platform: mqtt
  name: motion_event_average
  topic: 'motion/+/+/image-average'
- platform: mqtt
  name: motion_event_blend
  topic: 'motion/+/+/image-blend'
- platform: mqtt
  name: motion_event_animated_mask
  topic: 'motion/+/+/image-animated-mask'
- platform: mqtt
  name: motion_event_composite
  topic: 'motion/+/+/image-composite'
- platform: mqtt
  name: motion_event_animated
  topic: 'motion/+/+/image-animated'
- platform: mqtt
  name: motion_event_end
  topic: 'motion/+/+/image/end'

# per image
- platform: mqtt
  name: motion_image_last
  topic: 'motion/+/+/image'

- platform: mqtt
  name: motion_image_cropped
  topic: 'motion/+/+/image-cropped'

- platform: generic
  name: motion_end_picture
  verify_ssl: false
  limit_refetch_to_url_change: true
  still_image_url: >-
    {% if states('input_boolean.motion_snapshot') == 'on' %}
      {% set p = states('sensor.motion_end_snapshot') %}
    {% else %}
      {% set p = states('sensor.motion_end_picture') %}
    {% endif %}
    {% if p != 'unknown' and p != 'null' and p|length > 0 %}
      {{ p }}
    {% else %}{{ states('sensor.motion_nosignal_picture') }}{% endif %}
