###
### dogshedfront cameras
###

- platform: mjpeg
  name: motion_live_dogshedfront
  mjpeg_url: http://192.168.1.172/img/video.mjpeg
  verify_ssl: false
  authentication: basic
  username: !secret netcam-username
  password: !secret netcam-password

#- platform: mqtt
#  name: motion_current_dogshedfront
#  topic: 'motion/+/dogshedfront/image'
#
#- platform: mqtt
#  name: motion_event_average_dogshedfront
#  topic: 'motion/+/dogshedfront/image-average'
#
#- platform: mqtt
#  name: motion_event_blend_dogshedfront
#  topic: 'motion/+/dogshedfront/image-blend'
#
#- platform: mqtt
#  name: motion_event_animated_mask_dogshedfront
#  topic: 'motion/+/dogshedfront/image-animated-mask'
#
#- platform: mqtt
#  name: motion_event_composite_dogshedfront
#  topic: 'motion/+/dogshedfront/image-composite'
#
#- platform: mqtt
#  name: motion_event_cropped_dogshedfront
#  topic: 'motion/+/dogshedfront/image-cropped'

- platform: mqtt
  name: motion_event_animated_dogshedfront
  topic: 'motion/+/dogshedfront/image-animated'

- platform: mqtt
  name: motion_event_end_dogshedfront
  topic: 'motion/+/dogshedfront/image/end'

- platform: mqtt
  name: motion_event_annotated_dogshedfront
  topic: 'motion/+/dogshedfront/image/end/+'

###
# picture
###

- platform: generic
  name: motion_end_picture_dogshedfront
  verify_ssl: false
  limit_refetch_to_url_change: true
  still_image_url: >-
    {% if states('input_boolean.motion_snapshot') == 'on' %}
      {% set p = states('sensor.motion_end_snapshot_dogshedfront') %}
    {% else %}
      {% set p = states('sensor.motion_end_picture_dogshedfront') %}
    {% endif %}
    {% if p != 'unknown' and p != 'null' and p|length > 0 %}
      {{ p }}
    {% else %}{{ states('sensor.motion_nosignal_picture') }}{% endif %}

- platform: generic
  name: motion_annotated_picture_dogshedfront
  verify_ssl: false
  limit_refetch_to_url_change: true
  still_image_url: >-
    {% if states('input_boolean.motion_snapshot') == 'on' %}
      {% set p = states('sensor.motion_annotated_snapshot_dogshedfront') %}
    {% else %}
      {% set p = states('sensor.motion_annotated_picture_dogshedfront') %}
    {% endif %}
    {% if p != 'unknown' and p != 'null' and p|length > 0 %}
      {{ p }}
    {% else %}{{ states('sensor.motion_nosignal_picture') }}{% endif %}

- platform: generic
  name: motion_detected_picture_dogshedfront
  verify_ssl: false
  limit_refetch_to_url_change: true
  still_image_url: >-
    {% if states('input_boolean.motion_snapshot') == 'on' %}
      {% set p = states('sensor.motion_detected_snapshot_dogshedfront') %}
    {% else %}
      {% set p = states('sensor.motion_detected_picture_dogshedfront') %}
    {% endif %}
    {% if  p != 'unknown' and p != 'null' and p|length > 0 %}
      {{ p }}
    {% else %}{{ states('sensor.motion_nosignal_picture') }}{% endif %}

- platform: generic
  name: motion_detected_entity_picture_dogshedfront
  verify_ssl: false
  limit_refetch_to_url_change: true
  still_image_url: >-
    {% if states('input_boolean.motion_snapshot') == 'on' %}
      {% set p = states('sensor.motion_detected_entity_snapshot_dogshedfront') %}
    {% else %}
      {% set p = states('sensor.motion_detected_entity_picture_dogshedfront') %}
    {% endif %}
    {% if p != 'unknown' and p != 'null' and p|length > 0 %}
      {{ p }}
    {% else %}{{ states('sensor.motion_nosignal_picture') }}{% endif %}

###
# snapshot
###

- platform: generic
  name: motion_end_snapshot_dogshedfront
  verify_ssl: false
  still_image_url: >-
    {% set p = states('sensor.motion_end_snapshot_dogshedfront') %}
    {% if p != 'unknown' and p != 'null' and p|length > 0 %}
      {{ p }}
    {% else %}{{ states('sensor.motion_nosignal_picture') }}{% endif %}

- platform: generic
  name: motion_annotated_snapshot_dogshedfront
  verify_ssl: false
  still_image_url: >-
    {% set p = states('sensor.motion_annotated_snapshot_dogshedfront') %}
    {% if p != 'unknown' and p != 'null' and p|length > 0 %}
      {{ p }}
    {% else %}{{ states('sensor.motion_nosignal_picture') }}{% endif %}

- platform: generic
  name: motion_detected_snapshot_dogshedfront
  verify_ssl: false
  still_image_url: >-
    {% set p = states('sensor.motion_detected_snapshot_dogshedfront') %}
    {% if  p != 'unknown' and p != 'null' and p|length > 0 %}
      {{ p }}
    {% else %}{{ states('sensor.motion_nosignal_picture') }}{% endif %}

- platform: generic
  name: motion_detected_entity_snapshot_dogshedfront
  verify_ssl: false
  still_image_url: >-
    {% set p = states('sensor.motion_detected_entity_snapshot_dogshedfront') %}
    {% if p != 'unknown' and p != 'null' and p|length > 0 %}
      {{ p }}
    {% else %}{{ states('sensor.motion_nosignal_picture') }}{% endif %}
