###
### fireplace cameras
###

- platform: mjpeg
  name: motion_live_fireplace
  mjpeg_url: http://192.168.1.166/img/video.mjpeg
  verify_ssl: false
  authentication: basic
  username: !secret netcam-username
  password: !secret netcam-password

#- platform: mqtt
#  name: motion_current_fireplace
#  topic: 'motion/+/fireplace/image'
#
#- platform: mqtt
#  name: motion_event_average_fireplace
#  topic: 'motion/+/fireplace/image-average'
#
#- platform: mqtt
#  name: motion_event_blend_fireplace
#  topic: 'motion/+/fireplace/image-blend'
#
#- platform: mqtt
#  name: motion_event_animated_mask_fireplace
#  topic: 'motion/+/fireplace/image-animated-mask'
#
#- platform: mqtt
#  name: motion_event_composite_fireplace
#  topic: 'motion/+/fireplace/image-composite'
#
#- platform: mqtt
#  name: motion_event_cropped_fireplace
#  topic: 'motion/+/fireplace/image-cropped'

- platform: mqtt
  name: motion_event_animated_fireplace
  topic: 'motion/+/fireplace/image-animated'

- platform: mqtt
  name: motion_event_end_fireplace
  topic: 'motion/+/fireplace/image/end'

- platform: mqtt
  name: motion_event_annotated_fireplace
  topic: 'motion/+/fireplace/image/end/+'

###
# picture
###

- platform: generic
  name: motion_end_picture_fireplace
  verify_ssl: false
  limit_refetch_to_url_change: true
  still_image_url: >-
    {% if states('input_boolean.motion_snapshot') == 'on' %}
      {% set p = states('sensor.motion_end_snapshot_fireplace') %}
    {% else %}
      {% set p = states('sensor.motion_end_picture_fireplace') %}
    {% endif %}
    {% if p != 'unknown' and p != 'null' and p|length > 0 %}
      {{ p }}
    {% else %}{{ states('sensor.motion_nosignal_picture') }}{% endif %}

- platform: generic
  name: motion_annotated_picture_fireplace
  verify_ssl: false
  limit_refetch_to_url_change: true
  still_image_url: >-
    {% if states('input_boolean.motion_snapshot') == 'on' %}
      {% set p = states('sensor.motion_annotated_snapshot_fireplace') %}
    {% else %}
      {% set p = states('sensor.motion_annotated_picture_fireplace') %}
    {% endif %}
    {% if p != 'unknown' and p != 'null' and p|length > 0 %}
      {{ p }}
    {% else %}{{ states('sensor.motion_nosignal_picture') }}{% endif %}

- platform: generic
  name: motion_detected_picture_fireplace
  verify_ssl: false
  limit_refetch_to_url_change: true
  still_image_url: >-
    {% if states('input_boolean.motion_snapshot') == 'on' %}
      {% set p = states('sensor.motion_detected_snapshot_fireplace') %}
    {% else %}
      {% set p = states('sensor.motion_detected_picture_fireplace') %}
    {% endif %}
    {% if  p != 'unknown' and p != 'null' and p|length > 0 %}
      {{ p }}
    {% else %}{{ states('sensor.motion_nosignal_picture') }}{% endif %}

- platform: generic
  name: motion_detected_entity_picture_fireplace
  verify_ssl: false
  limit_refetch_to_url_change: true
  still_image_url: >-
    {% if states('input_boolean.motion_snapshot') == 'on' %}
      {% set p = states('sensor.motion_detected_entity_snapshot_fireplace') %}
    {% else %}
      {% set p = states('sensor.motion_detected_entity_picture_fireplace') %}
    {% endif %}
    {% if p != 'unknown' and p != 'null' and p|length > 0 %}
      {{ p }}
    {% else %}{{ states('sensor.motion_nosignal_picture') }}{% endif %}

###
# snapshot
###

- platform: generic
  name: motion_end_snapshot_fireplace
  verify_ssl: false
  still_image_url: >-
    {% set p = states('sensor.motion_end_snapshot_fireplace') %}
    {% if p != 'unknown' and p != 'null' and p|length > 0 %}
      {{ p }}
    {% else %}{{ states('sensor.motion_nosignal_picture') }}{% endif %}

- platform: generic
  name: motion_annotated_snapshot_fireplace
  verify_ssl: false
  still_image_url: >-
    {% set p = states('sensor.motion_annotated_snapshot_fireplace') %}
    {% if p != 'unknown' and p != 'null' and p|length > 0 %}
      {{ p }}
    {% else %}{{ states('sensor.motion_nosignal_picture') }}{% endif %}

- platform: generic
  name: motion_detected_snapshot_fireplace
  verify_ssl: false
  still_image_url: >-
    {% set p = states('sensor.motion_detected_snapshot_fireplace') %}
    {% if  p != 'unknown' and p != 'null' and p|length > 0 %}
      {{ p }}
    {% else %}{{ states('sensor.motion_nosignal_picture') }}{% endif %}

- platform: generic
  name: motion_detected_entity_snapshot_fireplace
  verify_ssl: false
  still_image_url: >-
    {% set p = states('sensor.motion_detected_entity_snapshot_fireplace') %}
    {% if p != 'unknown' and p != 'null' and p|length > 0 %}
      {{ p }}
    {% else %}{{ states('sensor.motion_nosignal_picture') }}{% endif %}
