###
### laundry cameras
###

- platform: mjpeg
  name: motion_live_laundry
  mjpeg_url: http://192.168.1.177/img/video.mjpeg
  verify_ssl: false
  authentication: basic
  username: !secret netcam-username
  password: !secret netcam-password

#- platform: mqtt
#  name: motion_current_laundry
#  topic: 'motion/+/laundry/image'
#
#- platform: mqtt
#  name: motion_event_average_laundry
#  topic: 'motion/+/laundry/image-average'
#
#- platform: mqtt
#  name: motion_event_blend_laundry
#  topic: 'motion/+/laundry/image-blend'
#
#- platform: mqtt
#  name: motion_event_animated_mask_laundry
#  topic: 'motion/+/laundry/image-animated-mask'
#
#- platform: mqtt
#  name: motion_event_composite_laundry
#  topic: 'motion/+/laundry/image-composite'
#
#- platform: mqtt
#  name: motion_event_cropped_laundry
#  topic: 'motion/+/laundry/image-cropped'

- platform: mqtt
  name: motion_event_animated_laundry
  topic: 'motion/+/laundry/image-animated'

- platform: mqtt
  name: motion_event_end_laundry
  topic: 'motion/+/laundry/image/end'

- platform: mqtt
  name: motion_event_annotated_laundry
  topic: 'motion/+/laundry/image/end/+'

###
# picture
###

- platform: generic
  name: motion_end_picture_laundry
  verify_ssl: false
  limit_refetch_to_url_change: true
  still_image_url: >-
    {% if states('input_boolean.motion_snapshot') == 'on' %}
      {% set p = states('sensor.motion_end_snapshot_laundry') %}
    {% else %}
      {% set p = states('sensor.motion_end_picture_laundry') %}
    {% endif %}
    {% if p != 'unknown' and p != 'null' and p|length > 0 %}
      {{ p }}
    {% else %}{{ states('sensor.motion_nosignal_picture') }}{% endif %}

- platform: generic
  name: motion_annotated_picture_laundry
  verify_ssl: false
  limit_refetch_to_url_change: true
  still_image_url: >-
    {% if states('input_boolean.motion_snapshot') == 'on' %}
      {% set p = states('sensor.motion_annotated_snapshot_laundry') %}
    {% else %}
      {% set p = states('sensor.motion_annotated_picture_laundry') %}
    {% endif %}
    {% if p != 'unknown' and p != 'null' and p|length > 0 %}
      {{ p }}
    {% else %}{{ states('sensor.motion_nosignal_picture') }}{% endif %}

- platform: generic
  name: motion_detected_picture_laundry
  verify_ssl: false
  limit_refetch_to_url_change: true
  still_image_url: >-
    {% if states('input_boolean.motion_snapshot') == 'on' %}
      {% set p = states('sensor.motion_detected_snapshot_laundry') %}
    {% else %}
      {% set p = states('sensor.motion_detected_picture_laundry') %}
    {% endif %}
    {% if  p != 'unknown' and p != 'null' and p|length > 0 %}
      {{ p }}
    {% else %}{{ states('sensor.motion_nosignal_picture') }}{% endif %}

- platform: generic
  name: motion_detected_entity_picture_laundry
  verify_ssl: false
  limit_refetch_to_url_change: true
  still_image_url: >-
    {% if states('input_boolean.motion_snapshot') == 'on' %}
      {% set p = states('sensor.motion_detected_entity_snapshot_laundry') %}
    {% else %}
      {% set p = states('sensor.motion_detected_entity_picture_laundry') %}
    {% endif %}
    {% if p != 'unknown' and p != 'null' and p|length > 0 %}
      {{ p }}
    {% else %}{{ states('sensor.motion_nosignal_picture') }}{% endif %}

###
# snapshot
###

- platform: generic
  name: motion_end_snapshot_laundry
  verify_ssl: false
  still_image_url: >-
    {% set p = states('sensor.motion_end_snapshot_laundry') %}
    {% if p != 'unknown' and p != 'null' and p|length > 0 %}
      {{ p }}
    {% else %}{{ states('sensor.motion_nosignal_picture') }}{% endif %}

- platform: generic
  name: motion_annotated_snapshot_laundry
  verify_ssl: false
  still_image_url: >-
    {% set p = states('sensor.motion_annotated_snapshot_laundry') %}
    {% if p != 'unknown' and p != 'null' and p|length > 0 %}
      {{ p }}
    {% else %}{{ states('sensor.motion_nosignal_picture') }}{% endif %}

- platform: generic
  name: motion_detected_snapshot_laundry
  verify_ssl: false
  still_image_url: >-
    {% set p = states('sensor.motion_detected_snapshot_laundry') %}
    {% if  p != 'unknown' and p != 'null' and p|length > 0 %}
      {{ p }}
    {% else %}{{ states('sensor.motion_nosignal_picture') }}{% endif %}

- platform: generic
  name: motion_detected_entity_snapshot_laundry
  verify_ssl: false
  still_image_url: >-
    {% set p = states('sensor.motion_detected_entity_snapshot_laundry') %}
    {% if p != 'unknown' and p != 'null' and p|length > 0 %}
      {{ p }}
    {% else %}{{ states('sensor.motion_nosignal_picture') }}{% endif %}
