###
### shed cameras
###

- platform: mjpeg
  name: motion_live_shed
  mjpeg_url: http://192.168.1.97:8090/2
  verify_ssl: false
  authentication: basic
  username: username
  password: password

#- platform: mqtt
#  name: motion_current_shed
#  topic: 'motion/+/shed/image'
#
#- platform: mqtt
#  name: motion_event_average_shed
#  topic: 'motion/+/shed/image-average'
#
#- platform: mqtt
#  name: motion_event_blend_shed
#  topic: 'motion/+/shed/image-blend'
#
#- platform: mqtt
#  name: motion_event_animated_mask_shed
#  topic: 'motion/+/shed/image-animated-mask'
#
#- platform: mqtt
#  name: motion_event_composite_shed
#  topic: 'motion/+/shed/image-composite'
#
#- platform: mqtt
#  name: motion_event_cropped_shed
#  topic: 'motion/+/shed/image-cropped'

- platform: mqtt
  name: motion_event_animated_shed
  topic: 'motion/+/shed/image-animated'

- platform: mqtt
  name: motion_event_end_shed
  topic: 'motion/+/shed/image/end'

- platform: mqtt
  name: motion_event_annotated_shed
  topic: 'motion/+/shed/image/end/+'

###
# picture
###

- platform: generic
  name: motion_end_picture_shed
  verify_ssl: false
  limit_refetch_to_url_change: true
  still_image_url: >-
    {% if states('input_boolean.motion_snapshot') == 'on' %}
      {% set p = states('sensor.motion_end_snapshot_shed') %}
    {% else %}
      {% set p = states('sensor.motion_end_picture_shed') %}
    {% endif %}
    {% if p != 'unknown' and p != 'null' and p|length > 0 %}
      {{ p }}
    {% else %}{{ states('sensor.motion_nosignal_picture') }}{% endif %}

- platform: generic
  name: motion_annotated_picture_shed
  verify_ssl: false
  limit_refetch_to_url_change: true
  still_image_url: >-
    {% if states('input_boolean.motion_snapshot') == 'on' %}
      {% set p = states('sensor.motion_annotated_snapshot_shed') %}
    {% else %}
      {% set p = states('sensor.motion_annotated_picture_shed') %}
    {% endif %}
    {% if p != 'unknown' and p != 'null' and p|length > 0 %}
      {{ p }}
    {% else %}{{ states('sensor.motion_nosignal_picture') }}{% endif %}

- platform: generic
  name: motion_detected_picture_shed
  verify_ssl: false
  limit_refetch_to_url_change: true
  still_image_url: >-
    {% if states('input_boolean.motion_snapshot') == 'on' %}
      {% set p = states('sensor.motion_detected_snapshot_shed') %}
    {% else %}
      {% set p = states('sensor.motion_detected_picture_shed') %}
    {% endif %}
    {% if  p != 'unknown' and p != 'null' and p|length > 0 %}
      {{ p }}
    {% else %}{{ states('sensor.motion_nosignal_picture') }}{% endif %}

- platform: generic
  name: motion_detected_entity_picture_shed
  verify_ssl: false
  limit_refetch_to_url_change: true
  still_image_url: >-
    {% if states('input_boolean.motion_snapshot') == 'on' %}
      {% set p = states('sensor.motion_detected_entity_snapshot_shed') %}
    {% else %}
      {% set p = states('sensor.motion_detected_entity_picture_shed') %}
    {% endif %}
    {% if p != 'unknown' and p != 'null' and p|length > 0 %}
      {{ p }}
    {% else %}{{ states('sensor.motion_nosignal_picture') }}{% endif %}

###
# snapshot
###

- platform: generic
  name: motion_end_snapshot_shed
  verify_ssl: false
  still_image_url: >-
    {% set p = states('sensor.motion_end_snapshot_shed') %}
    {% if p != 'unknown' and p != 'null' and p|length > 0 %}
      {{ p }}
    {% else %}{{ states('sensor.motion_nosignal_picture') }}{% endif %}

- platform: generic
  name: motion_annotated_snapshot_shed
  verify_ssl: false
  still_image_url: >-
    {% set p = states('sensor.motion_annotated_snapshot_shed') %}
    {% if p != 'unknown' and p != 'null' and p|length > 0 %}
      {{ p }}
    {% else %}{{ states('sensor.motion_nosignal_picture') }}{% endif %}

- platform: generic
  name: motion_detected_snapshot_shed
  verify_ssl: false
  still_image_url: >-
    {% set p = states('sensor.motion_detected_snapshot_shed') %}
    {% if  p != 'unknown' and p != 'null' and p|length > 0 %}
      {{ p }}
    {% else %}{{ states('sensor.motion_nosignal_picture') }}{% endif %}

- platform: generic
  name: motion_detected_entity_snapshot_shed
  verify_ssl: false
  still_image_url: >-
    {% set p = states('sensor.motion_detected_entity_snapshot_shed') %}
    {% if p != 'unknown' and p != 'null' and p|length > 0 %}
      {{ p }}
    {% else %}{{ states('sensor.motion_nosignal_picture') }}{% endif %}
