###
### backyard cameras
###

- platform: mjpeg
  name: motion_live_backyard
  mjpeg_url: http://192.168.1.183/img/video.mjpeg
  verify_ssl: false
  authentication: basic
  username: !secret netcam-username
  password: !secret netcam-password

#- platform: mqtt
#  name: motion_current_backyard
#  topic: 'motion/+/backyard/image'
#
#- platform: mqtt
#  name: motion_event_average_backyard
#  topic: 'motion/+/backyard/image-average'
#
#- platform: mqtt
#  name: motion_event_blend_backyard
#  topic: 'motion/+/backyard/image-blend'
#
#- platform: mqtt
#  name: motion_event_animated_mask_backyard
#  topic: 'motion/+/backyard/image-animated-mask'
#
#- platform: mqtt
#  name: motion_event_composite_backyard
#  topic: 'motion/+/backyard/image-composite'
#
#- platform: mqtt
#  name: motion_event_cropped_backyard
#  topic: 'motion/+/backyard/image-cropped'

- platform: mqtt
  name: motion_event_animated_backyard
  topic: 'motion/+/backyard/image-animated'

- platform: mqtt
  name: motion_event_end_backyard
  topic: 'motion/+/backyard/image/end'

- platform: mqtt
  name: motion_event_annotated_backyard
  topic: 'motion/+/backyard/image/end/+'

###
# picture
###

- platform: generic
  name: motion_end_picture_backyard
  verify_ssl: false
  limit_refetch_to_url_change: true
  still_image_url: >-
    {% if states('input_boolean.motion_snapshot') == 'on' %}
      {% set p = states('sensor.motion_end_snapshot_backyard') %}
    {% else %}
      {% set p = states('sensor.motion_end_picture_backyard') %}
    {% endif %}
    {% if p != 'unknown' and p != 'null' and p|length > 0 %}
      {{ p }}
    {% else %}{{ states('sensor.motion_nosignal_picture') }}{% endif %}

- platform: generic
  name: motion_annotated_picture_backyard
  verify_ssl: false
  limit_refetch_to_url_change: true
  still_image_url: >-
    {% if states('input_boolean.motion_snapshot') == 'on' %}
      {% set p = states('sensor.motion_annotated_snapshot_backyard') %}
    {% else %}
      {% set p = states('sensor.motion_annotated_picture_backyard') %}
    {% endif %}
    {% if p != 'unknown' and p != 'null' and p|length > 0 %}
      {{ p }}
    {% else %}{{ states('sensor.motion_nosignal_picture') }}{% endif %}

- platform: generic
  name: motion_detected_picture_backyard
  verify_ssl: false
  limit_refetch_to_url_change: true
  still_image_url: >-
    {% if states('input_boolean.motion_snapshot') == 'on' %}
      {% set p = states('sensor.motion_detected_snapshot_backyard') %}
    {% else %}
      {% set p = states('sensor.motion_detected_picture_backyard') %}
    {% endif %}
    {% if  p != 'unknown' and p != 'null' and p|length > 0 %}
      {{ p }}
    {% else %}{{ states('sensor.motion_nosignal_picture') }}{% endif %}

- platform: generic
  name: motion_detected_entity_picture_backyard
  verify_ssl: false
  limit_refetch_to_url_change: true
  still_image_url: >-
    {% if states('input_boolean.motion_snapshot') == 'on' %}
      {% set p = states('sensor.motion_detected_entity_snapshot_backyard') %}
    {% else %}
      {% set p = states('sensor.motion_detected_entity_picture_backyard') %}
    {% endif %}
    {% if p != 'unknown' and p != 'null' and p|length > 0 %}
      {{ p }}
    {% else %}{{ states('sensor.motion_nosignal_picture') }}{% endif %}

###
# snapshot
###

- platform: generic
  name: motion_end_snapshot_backyard
  verify_ssl: false
  still_image_url: >-
    {% set p = states('sensor.motion_end_snapshot_backyard') %}
    {% if p != 'unknown' and p != 'null' and p|length > 0 %}
      {{ p }}
    {% else %}{{ states('sensor.motion_nosignal_picture') }}{% endif %}

- platform: generic
  name: motion_annotated_snapshot_backyard
  verify_ssl: false
  still_image_url: >-
    {% set p = states('sensor.motion_annotated_snapshot_backyard') %}
    {% if p != 'unknown' and p != 'null' and p|length > 0 %}
      {{ p }}
    {% else %}{{ states('sensor.motion_nosignal_picture') }}{% endif %}

- platform: generic
  name: motion_detected_snapshot_backyard
  verify_ssl: false
  still_image_url: >-
    {% set p = states('sensor.motion_detected_snapshot_backyard') %}
    {% if  p != 'unknown' and p != 'null' and p|length > 0 %}
      {{ p }}
    {% else %}{{ states('sensor.motion_nosignal_picture') }}{% endif %}

- platform: generic
  name: motion_detected_entity_snapshot_backyard
  verify_ssl: false
  still_image_url: >-
    {% set p = states('sensor.motion_detected_entity_snapshot_backyard') %}
    {% if p != 'unknown' and p != 'null' and p|length > 0 %}
      {{ p }}
    {% else %}{{ states('sensor.motion_nosignal_picture') }}{% endif %}
