###
### dogpond cameras
###

- platform: mjpeg
  name: motion_live_dogpond
  mjpeg_url: http://192.168.1.97:8090/3
  verify_ssl: false
  authentication: basic
  username: username
  password: password

#- platform: mqtt
#  name: motion_current_dogpond
#  topic: 'motion/+/dogpond/image'
#
#- platform: mqtt
#  name: motion_event_average_dogpond
#  topic: 'motion/+/dogpond/image-average'
#
#- platform: mqtt
#  name: motion_event_blend_dogpond
#  topic: 'motion/+/dogpond/image-blend'
#
#- platform: mqtt
#  name: motion_event_animated_mask_dogpond
#  topic: 'motion/+/dogpond/image-animated-mask'
#
#- platform: mqtt
#  name: motion_event_composite_dogpond
#  topic: 'motion/+/dogpond/image-composite'
#
#- platform: mqtt
#  name: motion_event_cropped_dogpond
#  topic: 'motion/+/dogpond/image-cropped'

- platform: mqtt
  name: motion_event_animated_dogpond
  topic: 'motion/+/dogpond/image-animated'

- platform: mqtt
  name: motion_event_end_dogpond
  topic: 'motion/+/dogpond/image/end'

- platform: mqtt
  name: motion_event_annotated_dogpond
  topic: 'motion/+/dogpond/image/end/+'

###
# picture
###

- platform: generic
  name: motion_end_picture_dogpond
  verify_ssl: false
  limit_refetch_to_url_change: true
  still_image_url: >-
    {% if states('input_boolean.motion_snapshot') == 'on' %}
      {% set p = states('sensor.motion_end_snapshot_dogpond') %}
    {% else %}
      {% set p = states('sensor.motion_end_picture_dogpond') %}
    {% endif %}
    {% if p != 'unknown' and p != 'null' and p|length > 0 %}
      {{ p }}
    {% else %}{{ states('sensor.motion_nosignal_picture') }}{% endif %}

- platform: generic
  name: motion_annotated_picture_dogpond
  verify_ssl: false
  limit_refetch_to_url_change: true
  still_image_url: >-
    {% if states('input_boolean.motion_snapshot') == 'on' %}
      {% set p = states('sensor.motion_annotated_snapshot_dogpond') %}
    {% else %}
      {% set p = states('sensor.motion_annotated_picture_dogpond') %}
    {% endif %}
    {% if p != 'unknown' and p != 'null' and p|length > 0 %}
      {{ p }}
    {% else %}{{ states('sensor.motion_nosignal_picture') }}{% endif %}

- platform: generic
  name: motion_detected_picture_dogpond
  verify_ssl: false
  limit_refetch_to_url_change: true
  still_image_url: >-
    {% if states('input_boolean.motion_snapshot') == 'on' %}
      {% set p = states('sensor.motion_detected_snapshot_dogpond') %}
    {% else %}
      {% set p = states('sensor.motion_detected_picture_dogpond') %}
    {% endif %}
    {% if  p != 'unknown' and p != 'null' and p|length > 0 %}
      {{ p }}
    {% else %}{{ states('sensor.motion_nosignal_picture') }}{% endif %}

- platform: generic
  name: motion_detected_entity_picture_dogpond
  verify_ssl: false
  limit_refetch_to_url_change: true
  still_image_url: >-
    {% if states('input_boolean.motion_snapshot') == 'on' %}
      {% set p = states('sensor.motion_detected_entity_snapshot_dogpond') %}
    {% else %}
      {% set p = states('sensor.motion_detected_entity_picture_dogpond') %}
    {% endif %}
    {% if p != 'unknown' and p != 'null' and p|length > 0 %}
      {{ p }}
    {% else %}{{ states('sensor.motion_nosignal_picture') }}{% endif %}

###
# snapshot
###

- platform: generic
  name: motion_end_snapshot_dogpond
  verify_ssl: false
  still_image_url: >-
    {% set p = states('sensor.motion_end_snapshot_dogpond') %}
    {% if p != 'unknown' and p != 'null' and p|length > 0 %}
      {{ p }}
    {% else %}{{ states('sensor.motion_nosignal_picture') }}{% endif %}

- platform: generic
  name: motion_annotated_snapshot_dogpond
  verify_ssl: false
  still_image_url: >-
    {% set p = states('sensor.motion_annotated_snapshot_dogpond') %}
    {% if p != 'unknown' and p != 'null' and p|length > 0 %}
      {{ p }}
    {% else %}{{ states('sensor.motion_nosignal_picture') }}{% endif %}

- platform: generic
  name: motion_detected_snapshot_dogpond
  verify_ssl: false
  still_image_url: >-
    {% set p = states('sensor.motion_detected_snapshot_dogpond') %}
    {% if  p != 'unknown' and p != 'null' and p|length > 0 %}
      {{ p }}
    {% else %}{{ states('sensor.motion_nosignal_picture') }}{% endif %}

- platform: generic
  name: motion_detected_entity_snapshot_dogpond
  verify_ssl: false
  still_image_url: >-
    {% set p = states('sensor.motion_detected_entity_snapshot_dogpond') %}
    {% if p != 'unknown' and p != 'null' and p|length > 0 %}
      {{ p }}
    {% else %}{{ states('sensor.motion_nosignal_picture') }}{% endif %}
