###
### woodshed cameras
###

- platform: mjpeg
  name: motion_live_woodshed
  mjpeg_url: http://192.168.1.163/img/video.mjpeg
  verify_ssl: false
  authentication: basic
  username: !secret netcam-username
  password: !secret netcam-password

#- platform: mqtt
#  name: motion_current_woodshed
#  topic: 'motion/+/woodshed/image'
#
#- platform: mqtt
#  name: motion_event_average_woodshed
#  topic: 'motion/+/woodshed/image-average'
#
#- platform: mqtt
#  name: motion_event_blend_woodshed
#  topic: 'motion/+/woodshed/image-blend'
#
#- platform: mqtt
#  name: motion_event_animated_mask_woodshed
#  topic: 'motion/+/woodshed/image-animated-mask'
#
#- platform: mqtt
#  name: motion_event_composite_woodshed
#  topic: 'motion/+/woodshed/image-composite'
#
#- platform: mqtt
#  name: motion_event_cropped_woodshed
#  topic: 'motion/+/woodshed/image-cropped'

- platform: mqtt
  name: motion_event_animated_woodshed
  topic: 'motion/+/woodshed/image-animated'

- platform: mqtt
  name: motion_event_end_woodshed
  topic: 'motion/+/woodshed/image/end'

- platform: mqtt
  name: motion_event_annotated_woodshed
  topic: 'motion/+/woodshed/image/end/+'

###
# picture
###

- platform: generic
  name: motion_end_picture_woodshed
  verify_ssl: false
  limit_refetch_to_url_change: true
  still_image_url: >-
    {% if states('input_boolean.motion_snapshot') == 'on' %}
      {% set p = states('sensor.motion_end_snapshot_woodshed') %}
    {% else %}
      {% set p = states('sensor.motion_end_picture_woodshed') %}
    {% endif %}
    {% if p != 'unknown' and p != 'null' and p|length > 0 %}
      {{ p }}
    {% else %}{{ states('sensor.motion_nosignal_picture') }}{% endif %}

- platform: generic
  name: motion_annotated_picture_woodshed
  verify_ssl: false
  limit_refetch_to_url_change: true
  still_image_url: >-
    {% if states('input_boolean.motion_snapshot') == 'on' %}
      {% set p = states('sensor.motion_annotated_snapshot_woodshed') %}
    {% else %}
      {% set p = states('sensor.motion_annotated_picture_woodshed') %}
    {% endif %}
    {% if p != 'unknown' and p != 'null' and p|length > 0 %}
      {{ p }}
    {% else %}{{ states('sensor.motion_nosignal_picture') }}{% endif %}

- platform: generic
  name: motion_detected_picture_woodshed
  verify_ssl: false
  limit_refetch_to_url_change: true
  still_image_url: >-
    {% if states('input_boolean.motion_snapshot') == 'on' %}
      {% set p = states('sensor.motion_detected_snapshot_woodshed') %}
    {% else %}
      {% set p = states('sensor.motion_detected_picture_woodshed') %}
    {% endif %}
    {% if  p != 'unknown' and p != 'null' and p|length > 0 %}
      {{ p }}
    {% else %}{{ states('sensor.motion_nosignal_picture') }}{% endif %}

- platform: generic
  name: motion_detected_entity_picture_woodshed
  verify_ssl: false
  limit_refetch_to_url_change: true
  still_image_url: >-
    {% if states('input_boolean.motion_snapshot') == 'on' %}
      {% set p = states('sensor.motion_detected_entity_snapshot_woodshed') %}
    {% else %}
      {% set p = states('sensor.motion_detected_entity_picture_woodshed') %}
    {% endif %}
    {% if p != 'unknown' and p != 'null' and p|length > 0 %}
      {{ p }}
    {% else %}{{ states('sensor.motion_nosignal_picture') }}{% endif %}

###
# snapshot
###

- platform: generic
  name: motion_end_snapshot_woodshed
  verify_ssl: false
  still_image_url: >-
    {% set p = states('sensor.motion_end_snapshot_woodshed') %}
    {% if p != 'unknown' and p != 'null' and p|length > 0 %}
      {{ p }}
    {% else %}{{ states('sensor.motion_nosignal_picture') }}{% endif %}

- platform: generic
  name: motion_annotated_snapshot_woodshed
  verify_ssl: false
  still_image_url: >-
    {% set p = states('sensor.motion_annotated_snapshot_woodshed') %}
    {% if p != 'unknown' and p != 'null' and p|length > 0 %}
      {{ p }}
    {% else %}{{ states('sensor.motion_nosignal_picture') }}{% endif %}

- platform: generic
  name: motion_detected_snapshot_woodshed
  verify_ssl: false
  still_image_url: >-
    {% set p = states('sensor.motion_detected_snapshot_woodshed') %}
    {% if  p != 'unknown' and p != 'null' and p|length > 0 %}
      {{ p }}
    {% else %}{{ states('sensor.motion_nosignal_picture') }}{% endif %}

- platform: generic
  name: motion_detected_entity_snapshot_woodshed
  verify_ssl: false
  still_image_url: >-
    {% set p = states('sensor.motion_detected_entity_snapshot_woodshed') %}
    {% if p != 'unknown' and p != 'null' and p|length > 0 %}
      {{ p }}
    {% else %}{{ states('sensor.motion_nosignal_picture') }}{% endif %}
