###
### foyer cameras
###

- platform: mjpeg
  name: motion_live_foyer
  mjpeg_url: http://192.168.1.178/img/video.mjpeg
  verify_ssl: false
  authentication: basic
  username: !secret netcam-username
  password: !secret netcam-password

#- platform: mqtt
#  name: motion_current_foyer
#  topic: 'motion/+/foyer/image'
#
#- platform: mqtt
#  name: motion_event_average_foyer
#  topic: 'motion/+/foyer/image-average'
#
#- platform: mqtt
#  name: motion_event_blend_foyer
#  topic: 'motion/+/foyer/image-blend'
#
#- platform: mqtt
#  name: motion_event_animated_mask_foyer
#  topic: 'motion/+/foyer/image-animated-mask'
#
#- platform: mqtt
#  name: motion_event_composite_foyer
#  topic: 'motion/+/foyer/image-composite'
#
#- platform: mqtt
#  name: motion_event_cropped_foyer
#  topic: 'motion/+/foyer/image-cropped'

- platform: mqtt
  name: motion_event_animated_foyer
  topic: 'motion/+/foyer/image-animated'

- platform: mqtt
  name: motion_event_end_foyer
  topic: 'motion/+/foyer/image/end'

- platform: mqtt
  name: motion_event_annotated_foyer
  topic: 'motion/+/foyer/image/end/+'

###
# picture
###

- platform: generic
  name: motion_end_picture_foyer
  verify_ssl: false
  limit_refetch_to_url_change: true
  still_image_url: >-
    {% if states('input_boolean.motion_snapshot') == 'on' %}
      {% set p = states('sensor.motion_end_snapshot_foyer') %}
    {% else %}
      {% set p = states('sensor.motion_end_picture_foyer') %}
    {% endif %}
    {% if p != 'unknown' and p != 'null' and p|length > 0 %}
      {{ p }}
    {% else %}{{ states('sensor.motion_nosignal_picture') }}{% endif %}

- platform: generic
  name: motion_annotated_picture_foyer
  verify_ssl: false
  limit_refetch_to_url_change: true
  still_image_url: >-
    {% if states('input_boolean.motion_snapshot') == 'on' %}
      {% set p = states('sensor.motion_annotated_snapshot_foyer') %}
    {% else %}
      {% set p = states('sensor.motion_annotated_picture_foyer') %}
    {% endif %}
    {% if p != 'unknown' and p != 'null' and p|length > 0 %}
      {{ p }}
    {% else %}{{ states('sensor.motion_nosignal_picture') }}{% endif %}

- platform: generic
  name: motion_detected_picture_foyer
  verify_ssl: false
  limit_refetch_to_url_change: true
  still_image_url: >-
    {% if states('input_boolean.motion_snapshot') == 'on' %}
      {% set p = states('sensor.motion_detected_snapshot_foyer') %}
    {% else %}
      {% set p = states('sensor.motion_detected_picture_foyer') %}
    {% endif %}
    {% if  p != 'unknown' and p != 'null' and p|length > 0 %}
      {{ p }}
    {% else %}{{ states('sensor.motion_nosignal_picture') }}{% endif %}

- platform: generic
  name: motion_detected_entity_picture_foyer
  verify_ssl: false
  limit_refetch_to_url_change: true
  still_image_url: >-
    {% if states('input_boolean.motion_snapshot') == 'on' %}
      {% set p = states('sensor.motion_detected_entity_snapshot_foyer') %}
    {% else %}
      {% set p = states('sensor.motion_detected_entity_picture_foyer') %}
    {% endif %}
    {% if p != 'unknown' and p != 'null' and p|length > 0 %}
      {{ p }}
    {% else %}{{ states('sensor.motion_nosignal_picture') }}{% endif %}

###
# snapshot
###

- platform: generic
  name: motion_end_snapshot_foyer
  verify_ssl: false
  still_image_url: >-
    {% set p = states('sensor.motion_end_snapshot_foyer') %}
    {% if p != 'unknown' and p != 'null' and p|length > 0 %}
      {{ p }}
    {% else %}{{ states('sensor.motion_nosignal_picture') }}{% endif %}

- platform: generic
  name: motion_annotated_snapshot_foyer
  verify_ssl: false
  still_image_url: >-
    {% set p = states('sensor.motion_annotated_snapshot_foyer') %}
    {% if p != 'unknown' and p != 'null' and p|length > 0 %}
      {{ p }}
    {% else %}{{ states('sensor.motion_nosignal_picture') }}{% endif %}

- platform: generic
  name: motion_detected_snapshot_foyer
  verify_ssl: false
  still_image_url: >-
    {% set p = states('sensor.motion_detected_snapshot_foyer') %}
    {% if  p != 'unknown' and p != 'null' and p|length > 0 %}
      {{ p }}
    {% else %}{{ states('sensor.motion_nosignal_picture') }}{% endif %}

- platform: generic
  name: motion_detected_entity_snapshot_foyer
  verify_ssl: false
  still_image_url: >-
    {% set p = states('sensor.motion_detected_entity_snapshot_foyer') %}
    {% if p != 'unknown' and p != 'null' and p|length > 0 %}
      {{ p }}
    {% else %}{{ states('sensor.motion_nosignal_picture') }}{% endif %}
