###
### frontwalk cameras
###

- platform: mjpeg
  name: motion_live_frontwalk
  mjpeg_url: http://192.168.1.179/img/video.mjpeg
  verify_ssl: false
  authentication: basic
  username: !secret netcam-username
  password: !secret netcam-password

#- platform: mqtt
#  name: motion_current_frontwalk
#  topic: 'motion/+/frontwalk/image'
#
#- platform: mqtt
#  name: motion_event_average_frontwalk
#  topic: 'motion/+/frontwalk/image-average'
#
#- platform: mqtt
#  name: motion_event_blend_frontwalk
#  topic: 'motion/+/frontwalk/image-blend'
#
#- platform: mqtt
#  name: motion_event_animated_mask_frontwalk
#  topic: 'motion/+/frontwalk/image-animated-mask'
#
#- platform: mqtt
#  name: motion_event_composite_frontwalk
#  topic: 'motion/+/frontwalk/image-composite'
#
#- platform: mqtt
#  name: motion_event_cropped_frontwalk
#  topic: 'motion/+/frontwalk/image-cropped'

- platform: mqtt
  name: motion_event_animated_frontwalk
  topic: 'motion/+/frontwalk/image-animated'

- platform: mqtt
  name: motion_event_end_frontwalk
  topic: 'motion/+/frontwalk/image/end'

- platform: mqtt
  name: motion_event_annotated_frontwalk
  topic: 'motion/+/frontwalk/image/end/+'

###
# picture
###

- platform: generic
  name: motion_end_picture_frontwalk
  verify_ssl: false
  limit_refetch_to_url_change: true
  still_image_url: >-
    {% if states('input_boolean.motion_snapshot') == 'on' %}
      {% set p = states('sensor.motion_end_snapshot_frontwalk') %}
    {% else %}
      {% set p = states('sensor.motion_end_picture_frontwalk') %}
    {% endif %}
    {% if p != 'unknown' and p != 'null' and p|length > 0 %}
      {{ p }}
    {% else %}{{ states('sensor.motion_nosignal_picture') }}{% endif %}

- platform: generic
  name: motion_annotated_picture_frontwalk
  verify_ssl: false
  limit_refetch_to_url_change: true
  still_image_url: >-
    {% if states('input_boolean.motion_snapshot') == 'on' %}
      {% set p = states('sensor.motion_annotated_snapshot_frontwalk') %}
    {% else %}
      {% set p = states('sensor.motion_annotated_picture_frontwalk') %}
    {% endif %}
    {% if p != 'unknown' and p != 'null' and p|length > 0 %}
      {{ p }}
    {% else %}{{ states('sensor.motion_nosignal_picture') }}{% endif %}

- platform: generic
  name: motion_detected_picture_frontwalk
  verify_ssl: false
  limit_refetch_to_url_change: true
  still_image_url: >-
    {% if states('input_boolean.motion_snapshot') == 'on' %}
      {% set p = states('sensor.motion_detected_snapshot_frontwalk') %}
    {% else %}
      {% set p = states('sensor.motion_detected_picture_frontwalk') %}
    {% endif %}
    {% if  p != 'unknown' and p != 'null' and p|length > 0 %}
      {{ p }}
    {% else %}{{ states('sensor.motion_nosignal_picture') }}{% endif %}

- platform: generic
  name: motion_detected_entity_picture_frontwalk
  verify_ssl: false
  limit_refetch_to_url_change: true
  still_image_url: >-
    {% if states('input_boolean.motion_snapshot') == 'on' %}
      {% set p = states('sensor.motion_detected_entity_snapshot_frontwalk') %}
    {% else %}
      {% set p = states('sensor.motion_detected_entity_picture_frontwalk') %}
    {% endif %}
    {% if p != 'unknown' and p != 'null' and p|length > 0 %}
      {{ p }}
    {% else %}{{ states('sensor.motion_nosignal_picture') }}{% endif %}

###
# snapshot
###

- platform: generic
  name: motion_end_snapshot_frontwalk
  verify_ssl: false
  still_image_url: >-
    {% set p = states('sensor.motion_end_snapshot_frontwalk') %}
    {% if p != 'unknown' and p != 'null' and p|length > 0 %}
      {{ p }}
    {% else %}{{ states('sensor.motion_nosignal_picture') }}{% endif %}

- platform: generic
  name: motion_annotated_snapshot_frontwalk
  verify_ssl: false
  still_image_url: >-
    {% set p = states('sensor.motion_annotated_snapshot_frontwalk') %}
    {% if p != 'unknown' and p != 'null' and p|length > 0 %}
      {{ p }}
    {% else %}{{ states('sensor.motion_nosignal_picture') }}{% endif %}

- platform: generic
  name: motion_detected_snapshot_frontwalk
  verify_ssl: false
  still_image_url: >-
    {% set p = states('sensor.motion_detected_snapshot_frontwalk') %}
    {% if  p != 'unknown' and p != 'null' and p|length > 0 %}
      {{ p }}
    {% else %}{{ states('sensor.motion_nosignal_picture') }}{% endif %}

- platform: generic
  name: motion_detected_entity_snapshot_frontwalk
  verify_ssl: false
  still_image_url: >-
    {% set p = states('sensor.motion_detected_entity_snapshot_frontwalk') %}
    {% if p != 'unknown' and p != 'null' and p|length > 0 %}
      {{ p }}
    {% else %}{{ states('sensor.motion_nosignal_picture') }}{% endif %}
