###
### poolcam cameras
###

- platform: mjpeg
  name: motion_live_poolcam
  mjpeg_url: http://192.168.1.251:8090/1
  verify_ssl: false
  authentication: basic
  username: username
  password: password

#- platform: mqtt
#  name: motion_current_poolcam
#  topic: 'motion/+/poolcam/image'
#
#- platform: mqtt
#  name: motion_event_average_poolcam
#  topic: 'motion/+/poolcam/image-average'
#
#- platform: mqtt
#  name: motion_event_blend_poolcam
#  topic: 'motion/+/poolcam/image-blend'
#
#- platform: mqtt
#  name: motion_event_animated_mask_poolcam
#  topic: 'motion/+/poolcam/image-animated-mask'
#
#- platform: mqtt
#  name: motion_event_composite_poolcam
#  topic: 'motion/+/poolcam/image-composite'
#
#- platform: mqtt
#  name: motion_event_cropped_poolcam
#  topic: 'motion/+/poolcam/image-cropped'

- platform: mqtt
  name: motion_event_animated_poolcam
  topic: 'motion/+/poolcam/image-animated'

- platform: mqtt
  name: motion_event_end_poolcam
  topic: 'motion/+/poolcam/image/end'

- platform: mqtt
  name: motion_event_annotated_poolcam
  topic: 'motion/+/poolcam/image/end/+'

###
# picture
###

- platform: generic
  name: motion_end_picture_poolcam
  verify_ssl: false
  limit_refetch_to_url_change: true
  still_image_url: >-
    {% if states('input_boolean.motion_snapshot') == 'on' %}
      {% set p = states('sensor.motion_end_snapshot_poolcam') %}
    {% else %}
      {% set p = states('sensor.motion_end_picture_poolcam') %}
    {% endif %}
    {% if p != 'unknown' and p != 'null' and p|length > 0 %}
      {{ p }}
    {% else %}{{ states('sensor.motion_nosignal_picture') }}{% endif %}

- platform: generic
  name: motion_annotated_picture_poolcam
  verify_ssl: false
  limit_refetch_to_url_change: true
  still_image_url: >-
    {% if states('input_boolean.motion_snapshot') == 'on' %}
      {% set p = states('sensor.motion_annotated_snapshot_poolcam') %}
    {% else %}
      {% set p = states('sensor.motion_annotated_picture_poolcam') %}
    {% endif %}
    {% if p != 'unknown' and p != 'null' and p|length > 0 %}
      {{ p }}
    {% else %}{{ states('sensor.motion_nosignal_picture') }}{% endif %}

- platform: generic
  name: motion_detected_picture_poolcam
  verify_ssl: false
  limit_refetch_to_url_change: true
  still_image_url: >-
    {% if states('input_boolean.motion_snapshot') == 'on' %}
      {% set p = states('sensor.motion_detected_snapshot_poolcam') %}
    {% else %}
      {% set p = states('sensor.motion_detected_picture_poolcam') %}
    {% endif %}
    {% if  p != 'unknown' and p != 'null' and p|length > 0 %}
      {{ p }}
    {% else %}{{ states('sensor.motion_nosignal_picture') }}{% endif %}

- platform: generic
  name: motion_detected_entity_picture_poolcam
  verify_ssl: false
  limit_refetch_to_url_change: true
  still_image_url: >-
    {% if states('input_boolean.motion_snapshot') == 'on' %}
      {% set p = states('sensor.motion_detected_entity_snapshot_poolcam') %}
    {% else %}
      {% set p = states('sensor.motion_detected_entity_picture_poolcam') %}
    {% endif %}
    {% if p != 'unknown' and p != 'null' and p|length > 0 %}
      {{ p }}
    {% else %}{{ states('sensor.motion_nosignal_picture') }}{% endif %}

###
# snapshot
###

- platform: generic
  name: motion_end_snapshot_poolcam
  verify_ssl: false
  still_image_url: >-
    {% set p = states('sensor.motion_end_snapshot_poolcam') %}
    {% if p != 'unknown' and p != 'null' and p|length > 0 %}
      {{ p }}
    {% else %}{{ states('sensor.motion_nosignal_picture') }}{% endif %}

- platform: generic
  name: motion_annotated_snapshot_poolcam
  verify_ssl: false
  still_image_url: >-
    {% set p = states('sensor.motion_annotated_snapshot_poolcam') %}
    {% if p != 'unknown' and p != 'null' and p|length > 0 %}
      {{ p }}
    {% else %}{{ states('sensor.motion_nosignal_picture') }}{% endif %}

- platform: generic
  name: motion_detected_snapshot_poolcam
  verify_ssl: false
  still_image_url: >-
    {% set p = states('sensor.motion_detected_snapshot_poolcam') %}
    {% if  p != 'unknown' and p != 'null' and p|length > 0 %}
      {{ p }}
    {% else %}{{ states('sensor.motion_nosignal_picture') }}{% endif %}

- platform: generic
  name: motion_detected_entity_snapshot_poolcam
  verify_ssl: false
  still_image_url: >-
    {% set p = states('sensor.motion_detected_entity_snapshot_poolcam') %}
    {% if p != 'unknown' and p != 'null' and p|length > 0 %}
      {{ p }}
    {% else %}{{ states('sensor.motion_nosignal_picture') }}{% endif %}
