###
### interiorgate cameras
###

- platform: mjpeg
  name: motion_live_interiorgate
  mjpeg_url: http://192.168.1.251:8090/2
  verify_ssl: false
  authentication: basic
  username: username
  password: password

#- platform: mqtt
#  name: motion_current_interiorgate
#  topic: 'motion/+/interiorgate/image'
#
#- platform: mqtt
#  name: motion_event_average_interiorgate
#  topic: 'motion/+/interiorgate/image-average'
#
#- platform: mqtt
#  name: motion_event_blend_interiorgate
#  topic: 'motion/+/interiorgate/image-blend'
#
#- platform: mqtt
#  name: motion_event_animated_mask_interiorgate
#  topic: 'motion/+/interiorgate/image-animated-mask'
#
#- platform: mqtt
#  name: motion_event_composite_interiorgate
#  topic: 'motion/+/interiorgate/image-composite'
#
#- platform: mqtt
#  name: motion_event_cropped_interiorgate
#  topic: 'motion/+/interiorgate/image-cropped'

- platform: mqtt
  name: motion_event_animated_interiorgate
  topic: 'motion/+/interiorgate/image-animated'

- platform: mqtt
  name: motion_event_end_interiorgate
  topic: 'motion/+/interiorgate/image/end'

- platform: mqtt
  name: motion_event_annotated_interiorgate
  topic: 'motion/+/interiorgate/image/end/+'

###
# picture
###

- platform: generic
  name: motion_end_picture_interiorgate
  verify_ssl: false
  limit_refetch_to_url_change: true
  still_image_url: >-
    {% if states('input_boolean.motion_snapshot') == 'on' %}
      {% set p = states('sensor.motion_end_snapshot_interiorgate') %}
    {% else %}
      {% set p = states('sensor.motion_end_picture_interiorgate') %}
    {% endif %}
    {% if p != 'unknown' and p != 'null' and p|length > 0 %}
      {{ p }}
    {% else %}{{ states('sensor.motion_nosignal_picture') }}{% endif %}

- platform: generic
  name: motion_annotated_picture_interiorgate
  verify_ssl: false
  limit_refetch_to_url_change: true
  still_image_url: >-
    {% if states('input_boolean.motion_snapshot') == 'on' %}
      {% set p = states('sensor.motion_annotated_snapshot_interiorgate') %}
    {% else %}
      {% set p = states('sensor.motion_annotated_picture_interiorgate') %}
    {% endif %}
    {% if p != 'unknown' and p != 'null' and p|length > 0 %}
      {{ p }}
    {% else %}{{ states('sensor.motion_nosignal_picture') }}{% endif %}

- platform: generic
  name: motion_detected_picture_interiorgate
  verify_ssl: false
  limit_refetch_to_url_change: true
  still_image_url: >-
    {% if states('input_boolean.motion_snapshot') == 'on' %}
      {% set p = states('sensor.motion_detected_snapshot_interiorgate') %}
    {% else %}
      {% set p = states('sensor.motion_detected_picture_interiorgate') %}
    {% endif %}
    {% if  p != 'unknown' and p != 'null' and p|length > 0 %}
      {{ p }}
    {% else %}{{ states('sensor.motion_nosignal_picture') }}{% endif %}

- platform: generic
  name: motion_detected_entity_picture_interiorgate
  verify_ssl: false
  limit_refetch_to_url_change: true
  still_image_url: >-
    {% if states('input_boolean.motion_snapshot') == 'on' %}
      {% set p = states('sensor.motion_detected_entity_snapshot_interiorgate') %}
    {% else %}
      {% set p = states('sensor.motion_detected_entity_picture_interiorgate') %}
    {% endif %}
    {% if p != 'unknown' and p != 'null' and p|length > 0 %}
      {{ p }}
    {% else %}{{ states('sensor.motion_nosignal_picture') }}{% endif %}

###
# snapshot
###

- platform: generic
  name: motion_end_snapshot_interiorgate
  verify_ssl: false
  still_image_url: >-
    {% set p = states('sensor.motion_end_snapshot_interiorgate') %}
    {% if p != 'unknown' and p != 'null' and p|length > 0 %}
      {{ p }}
    {% else %}{{ states('sensor.motion_nosignal_picture') }}{% endif %}

- platform: generic
  name: motion_annotated_snapshot_interiorgate
  verify_ssl: false
  still_image_url: >-
    {% set p = states('sensor.motion_annotated_snapshot_interiorgate') %}
    {% if p != 'unknown' and p != 'null' and p|length > 0 %}
      {{ p }}
    {% else %}{{ states('sensor.motion_nosignal_picture') }}{% endif %}

- platform: generic
  name: motion_detected_snapshot_interiorgate
  verify_ssl: false
  still_image_url: >-
    {% set p = states('sensor.motion_detected_snapshot_interiorgate') %}
    {% if  p != 'unknown' and p != 'null' and p|length > 0 %}
      {{ p }}
    {% else %}{{ states('sensor.motion_nosignal_picture') }}{% endif %}

- platform: generic
  name: motion_detected_entity_snapshot_interiorgate
  verify_ssl: false
  still_image_url: >-
    {% set p = states('sensor.motion_detected_entity_snapshot_interiorgate') %}
    {% if p != 'unknown' and p != 'null' and p|length > 0 %}
      {{ p }}
    {% else %}{{ states('sensor.motion_nosignal_picture') }}{% endif %}
