###
### pondview cameras
###

- platform: mjpeg
  name: motion_live_pondview
  mjpeg_url: http://192.168.1.97:8090/4
  verify_ssl: false
  authentication: basic
  username: username
  password: password

#- platform: mqtt
#  name: motion_current_pondview
#  topic: 'motion/+/pondview/image'
#
#- platform: mqtt
#  name: motion_event_average_pondview
#  topic: 'motion/+/pondview/image-average'
#
#- platform: mqtt
#  name: motion_event_blend_pondview
#  topic: 'motion/+/pondview/image-blend'
#
#- platform: mqtt
#  name: motion_event_animated_mask_pondview
#  topic: 'motion/+/pondview/image-animated-mask'
#
#- platform: mqtt
#  name: motion_event_composite_pondview
#  topic: 'motion/+/pondview/image-composite'
#
#- platform: mqtt
#  name: motion_event_cropped_pondview
#  topic: 'motion/+/pondview/image-cropped'

- platform: mqtt
  name: motion_event_animated_pondview
  topic: 'motion/+/pondview/image-animated'

- platform: mqtt
  name: motion_event_end_pondview
  topic: 'motion/+/pondview/image/end'

- platform: mqtt
  name: motion_event_annotated_pondview
  topic: 'motion/+/pondview/image/end/+'

###
# picture
###

- platform: generic
  name: motion_end_picture_pondview
  verify_ssl: false
  limit_refetch_to_url_change: true
  still_image_url: >-
    {% if states('input_boolean.motion_snapshot') == 'on' %}
      {% set p = states('sensor.motion_end_snapshot_pondview') %}
    {% else %}
      {% set p = states('sensor.motion_end_picture_pondview') %}
    {% endif %}
    {% if p != 'unknown' and p != 'null' and p|length > 0 %}
      {{ p }}
    {% else %}{{ states('sensor.motion_nosignal_picture') }}{% endif %}

- platform: generic
  name: motion_annotated_picture_pondview
  verify_ssl: false
  limit_refetch_to_url_change: true
  still_image_url: >-
    {% if states('input_boolean.motion_snapshot') == 'on' %}
      {% set p = states('sensor.motion_annotated_snapshot_pondview') %}
    {% else %}
      {% set p = states('sensor.motion_annotated_picture_pondview') %}
    {% endif %}
    {% if p != 'unknown' and p != 'null' and p|length > 0 %}
      {{ p }}
    {% else %}{{ states('sensor.motion_nosignal_picture') }}{% endif %}

- platform: generic
  name: motion_detected_picture_pondview
  verify_ssl: false
  limit_refetch_to_url_change: true
  still_image_url: >-
    {% if states('input_boolean.motion_snapshot') == 'on' %}
      {% set p = states('sensor.motion_detected_snapshot_pondview') %}
    {% else %}
      {% set p = states('sensor.motion_detected_picture_pondview') %}
    {% endif %}
    {% if  p != 'unknown' and p != 'null' and p|length > 0 %}
      {{ p }}
    {% else %}{{ states('sensor.motion_nosignal_picture') }}{% endif %}

- platform: generic
  name: motion_detected_entity_picture_pondview
  verify_ssl: false
  limit_refetch_to_url_change: true
  still_image_url: >-
    {% if states('input_boolean.motion_snapshot') == 'on' %}
      {% set p = states('sensor.motion_detected_entity_snapshot_pondview') %}
    {% else %}
      {% set p = states('sensor.motion_detected_entity_picture_pondview') %}
    {% endif %}
    {% if p != 'unknown' and p != 'null' and p|length > 0 %}
      {{ p }}
    {% else %}{{ states('sensor.motion_nosignal_picture') }}{% endif %}

###
# snapshot
###

- platform: generic
  name: motion_end_snapshot_pondview
  verify_ssl: false
  still_image_url: >-
    {% set p = states('sensor.motion_end_snapshot_pondview') %}
    {% if p != 'unknown' and p != 'null' and p|length > 0 %}
      {{ p }}
    {% else %}{{ states('sensor.motion_nosignal_picture') }}{% endif %}

- platform: generic
  name: motion_annotated_snapshot_pondview
  verify_ssl: false
  still_image_url: >-
    {% set p = states('sensor.motion_annotated_snapshot_pondview') %}
    {% if p != 'unknown' and p != 'null' and p|length > 0 %}
      {{ p }}
    {% else %}{{ states('sensor.motion_nosignal_picture') }}{% endif %}

- platform: generic
  name: motion_detected_snapshot_pondview
  verify_ssl: false
  still_image_url: >-
    {% set p = states('sensor.motion_detected_snapshot_pondview') %}
    {% if  p != 'unknown' and p != 'null' and p|length > 0 %}
      {{ p }}
    {% else %}{{ states('sensor.motion_nosignal_picture') }}{% endif %}

- platform: generic
  name: motion_detected_entity_snapshot_pondview
  verify_ssl: false
  still_image_url: >-
    {% set p = states('sensor.motion_detected_entity_snapshot_pondview') %}
    {% if p != 'unknown' and p != 'null' and p|length > 0 %}
      {{ p }}
    {% else %}{{ states('sensor.motion_nosignal_picture') }}{% endif %}
