###
## group/default.yaml
###

default_view:
  name: HOME
  view: true
  control: hidden
  icon: mdi:home
  entities:
    - group.info
    - group.motion_cameras
    - group.motion_history_graphs
    - group.intranet_link
    - group.internet_link
    - group.weather

motion_cameras:
  name: Motion Cameras
  view: false
  control: hidden
  entities:
    - camera.motion_event_end
    - camera.motion_event_annotated
    - camera.motion_event_animated
    - camera.motion_annotated_picture
    - camera.motion_detected_picture
    - camera.motion_detected_entity_picture

motion_history_graphs:
  name: History Graphs
  view: false
  control: hidden
  entities:
    - history_graph.motion_counter
    - history_graph.motion_count
    - history_graph.motion_percent

info:
  name: Info
  view: false
  control: hidden
  entities:
    - sensor.date
    - sensor.time
    - sensor.host_lan_ip
    - sensor.host_wan_ip
    - sun.sun
