###
### webcam DEVICE_TRACKER
###

- platform: mqtt
  devices:
    motion_webcam_frontdoor: 'motion/tracker/webcam/frontdoor'
    motion_webcam_backyard: 'motion/tracker/webcam/backyard'
    motion_webcam_diningroom: 'motion/tracker/webcam/diningroom'
    motion_webcam_dogpond: 'motion/tracker/webcam/dogpond'
    motion_webcam_dogshed: 'motion/tracker/webcam/dogshed'
    motion_webcam_dogshedfront: 'motion/tracker/webcam/dogshedfront'
    motion_webcam_dogshedmiddle: 'motion/tracker/webcam/dogshedmiddle'
    motion_webcam_dogyard: 'motion/tracker/webcam/dogyard'
    motion_webcam_fireplace: 'motion/tracker/webcam/fireplace'
    motion_webcam_foyer: 'motion/tracker/webcam/foyer'
    motion_webcam_frontwalk: 'motion/tracker/webcam/frontwalk'
    motion_webcam_gravelpad: 'motion/tracker/webcam/gravelpad'
    motion_webcam_laundry: 'motion/tracker/webcam/laundry'
    motion_webcam_livingroom: 'motion/tracker/webcam/livingroom'
    motion_webcam_phexterior: 'motion/tracker/webcam/phexterior'
    motion_webcam_pondview: 'motion/tracker/webcam/pondview'
    motion_webcam_sideyard: 'motion/tracker/webcam/sideyard'
    motion_webcam_upperpathgate: 'motion/tracker/webcam/upperpathgate'
    motion_webcam_woodshed: 'motion/tracker/webcam/woodshed'
